# Generated by Django 5.1.7 on 2025-03-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artwork',
            old_name='artist_id',
            new_name='artist',
        ),
        migrations.AddField(
            model_name='artwork',
            name='1741540585.083459',
            field=models.ImageField(default='AH000', upload_to='media/'),
            preserve_default=False,
        ),
    ]
