# Generated by Django 5.1.7 on 2025-03-09 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_artist_id_artwork_artist_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artwork',
            old_name='1741540585.083459',
            new_name='1741540743.8062348',
        ),
    ]
