# Generated by Django 5.1.7 on 2025-03-09 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rename_1741540585_083459_artwork_1741540743_8062348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artwork',
            old_name='1741540743.8062348',
            new_name='1741541726.083429',
        ),
    ]
