# Generated by Django 5.1.7 on 2025-03-09 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_rename_1741540743_8062348_artwork_1741541726_083429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='artist_id',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='artwork',
            old_name='1741541726.083429',
            new_name='1741541894.2590952',
        ),
    ]
