# Generated by Django 5.1.7 on 2025-03-09 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_rename_artist_id_artist_artist_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artwork',
            old_name='1741541894.2590952',
            new_name='1741541927.3826458',
        ),
    ]
