# Generated by Django 5.1.7 on 2025-03-09 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_rename_1741541894_2590952_artwork_1741541927_3826458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='1741541927.3826458',
        ),
    ]
