# Generated by Django 5.1.7 on 2025-03-09 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_remove_artwork_1741541927_3826458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='artist',
            new_name='artist_id',
        ),
    ]
