# Generated by Django 5.1.7 on 2025-03-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_rename_artist_artist_artist_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='storage_city',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
