# Generated by Django 5.1.7 on 2025-03-09 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_storage_storage_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='storage',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='website.storage'),
            preserve_default=False,
        ),
    ]
